from __future__ import annotations
from typing_extensions import Self

class GraphDiffusion:
    def __init__(self: Self, device: str) -> None: ...
    def set_num_demos(self: Self, num_demos: int) -> None: ...
    def set_num_diffusion_steps(self: Self, num_diffusion_steps: int) -> None: ...
    def predict_actions(self: Self, full_sample: dict) -> tuple: ...


def sample_to_cond_demo(sample: dict, num_waypoints: int, num_points: int) -> dict:
    ...
